-- MySQL Script generated by MySQL Workbench
-- Mon Jul 18 17:43:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema marketsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema marketsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `marketsdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `marketsdb` ;

-- -----------------------------------------------------
-- Table `marketsdb`.`market`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketsdb`.`market` (
  `market_id` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(1024) NOT NULL,
  `number_of_stalls` INT NOT NULL,
  `nearest_mrt` VARCHAR(255) NOT NULL,
  `market_name` VARCHAR(255) NULL,
  PRIMARY KEY (`market_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketsdb`.`stall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketsdb`.`stall` (
  `stall_id` INT NOT NULL AUTO_INCREMENT,
  `type_produce` VARCHAR(45) NOT NULL,
  `market_id` INT NOT NULL,
  `stall_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`stall_id`),
  INDEX `market_id_idx` (`market_id` ASC) VISIBLE,
  CONSTRAINT `market_id`
    FOREIGN KEY (`market_id`)
    REFERENCES `marketsdb`.`market` (`market_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketsdb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketsdb`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(255) NOT NULL,
  `price` DECIMAL NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `stall_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `stall_id_idx` (`stall_id` ASC) VISIBLE,
  CONSTRAINT `stall_id`
    FOREIGN KEY (`stall_id`)
    REFERENCES `marketsdb`.`stall` (`stall_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
